// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnX92fG8honOi0KpB54c8NdnLcqqUNWo',
    appId: '1:154262156893:android:3e3e7f24329914ea883fb4',
    messagingSenderId: '154262156893',
    projectId: 'valorantapp-af847',
    databaseURL: 'https://valorantapp-af847-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'valorantapp-af847.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaqd2WRRzqGxqTPSOcVrwsqU9AbGOh0pA',
    appId: '1:154262156893:web:e7246dc708539a16883fb4',
    messagingSenderId: '154262156893',
    projectId: 'valorantapp-af847',
    authDomain: 'valorantapp-af847.firebaseapp.com',
    databaseURL: 'https://valorantapp-af847-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'valorantapp-af847.appspot.com',
    measurementId: 'G-ZCQGR2EV6B',
  );
}
